
# Ruff configuration
target-version = "py312"
line-length = 88
exclude = ["tests", "scripts", "data"]

[lint]
# Enable:
# Pyflakes (F)
# pycodestyle (E, W)
# isort (I)
# flake8-print (T20) - Bans print statements
select = ["F", "E", "W", "I", "T20"]

# Ignore:
# E501 (line too long) - let black handle formatting
ignore = ["E501"]

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]
