import type { NativeUnifiedPayload } from '@/core/types/native';

function line(value: number | null) {
  return {
    value,
    source: 'sec_native' as const,
    confidence: 0.9,
    method: 'filed test double',
    concept: 'test',
    sources: [],
  };
}

function annualRow(year: number, revenue: number | null) {
  return {
    year,
    revenue: line(revenue),
    cost_of_revenue: line(0),
    gross_profit: line(0),
    ebit: line(revenue === null ? null : -1_000_000),
    ebitda: line(0),
    interest_expense: line(0),
    income_tax_expense: line(0),
    net_income: line(0),
    depreciation: line(0),
    stock_based_comp: line(0),
    cfo: line(0),
    capex: line(0),
    cash: line(10_000_000),
    current_debt: line(0),
    long_term_debt: line(0),
    debt: line(0),
    operating_lease_liability_current: line(0),
    operating_lease_liability_noncurrent: line(0),
    lease_liabilities: line(0),
    book_value: line(0),
    accounts_receivable: line(0),
    inventory: line(0),
    accounts_payable: line(0),
    total_assets: line(0),
    total_liabilities: line(0),
    retained_earnings: line(0),
    dividends_paid: line(0),
    non_controlling_interest: line(0),
    preferred_equity: line(0),
    marketable_securities: line(0),
    marketable_securities_current: line(0),
    marketable_securities_noncurrent: line(0),
    long_term_debt_current: line(0),
    commercial_paper: line(0),
    total_current_assets: line(0),
    other_current_assets: line(0),
    ppe_net: line(0),
    other_assets: line(0),
    other_liabilities: line(0),
    total_current_liabilities: line(0),
    other_current_liabilities: line(0),
    deferred_revenue: line(0),
    research_and_development: line(0),
    general_and_administrative: line(0),
    marketing: line(0),
    rent: line(0),
    bad_debt: line(0),
    other_operating_expenses: line(0),
    deferred_tax: line(0),
    other_non_cash: line(0),
    nwc_change: line(0),
    operating_net_working_capital: line(0),
    fcff: line(0),
    balance_sheet_check: line(0),
    tax_rate: line(0),
    shares: line(10_000_000),
  };
}

function pipelineAsset(id: string) {
  return {
    asset_id: id,
    asset_name: id,
    stage: 'Phase 2',
    development_status: 'disclosed' as const,
    partner: null,
    accession_number: '0000000000-26-000001',
    filing_date: '2026-02-01',
    report_date: '2025-12-31',
    form: '10-K',
    primary_document: 'tst-2025x10k.htm',
    source_statement: 'pipeline table',
  };
}

export function biotechPayload(revenue: number | null): NativeUnifiedPayload {
  const annual = [2023, 2024, 2025].map((year) => annualRow(year, revenue));
  return {
    profile: { cik: '0000000000', ticker: 'TST', name: 'Test Bio' },
    financials_native: {
      ticker: 'TST',
      cik: '0000000000',
      name: 'Test Bio',
      source: 'edgartools_native',
      periods_requested: 5,
      statements: {},
      key_metrics: {},
      pipeline_assets: [pipelineAsset('A1'), pipelineAsset('A2'), pipelineAsset('A3'), pipelineAsset('A4'), pipelineAsset('A5')],
      fetched_at_ms: 1,
    },
    canonical_financials: {
      currency: 'USD',
      scale: 'units',
      metadata: {},
      years: [2023, 2024, 2025],
      annual,
      latest: annual[2]!,
      quality: {},
    },
    model_eligibility: {
      company_type: 'high_growth',
      preferred_model: 'biotech_pipeline_rnpv',
      allowed_models: ['biotech_pipeline_rnpv'],
      blocked_models: [],
      supported_by_current_engine: true,
      status: 'ready',
      model_route_available: true,
      missing_input_gaps: [],
    },
    market: {
      current_price: 10,
      market_cap: 1_000_000_000,
      shares_outstanding: 100_000_000,
      beta: 1.2,
      currency: 'USD',
      source: 'test',
      fetched_at_ms: Date.now(),
    },
    market_context: { risk_free_rate: 0.04, equity_risk_premium: 0.05 },
    valuation_context: {
      risk_free_rate: 0.04,
      equity_risk_premium: 0.05,
      fetched_at_ms: Date.now(),
      treasury_rate_source: 'test',
      erp_source: 'test',
      as_of_date: '2026-02-01',
    },
    peers: [],
    insider_trades: [],
    source_metadata: {},
    data_quality: {},
    completeness: {
      has_financials: true,
      has_market: true,
      has_valuation_context: true,
      has_peers: true,
      has_insider_trades: false,
      degradation_level: 'none',
    },
  } as unknown as NativeUnifiedPayload;
}
